---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  vars:
    key_name: jenkins
  become_user: root
  tasks:
    - name: install jq, JSON parser
      yum:
        name: jq
        state: present